<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ims" nsURI="http://hyacinth.com/ims" nsPrefix="ims">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="3" eType="#//PersonRole"
        eOpposite="#//PersonRole/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sales" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/seller"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="purchases" upperBound="-1"
        eType="#//Transaction" eOpposite="#//Transaction/buyer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegularEmployee" eSuperTypes="#//EmployeeRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="Manager" eSuperTypes="#//EmployeeRole"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="seller" lowerBound="1"
        eType="#//Person" eOpposite="#//Person/sales"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buyer" lowerBound="1" eType="#//Person"
        eOpposite="#//Person/purchases"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amountPaid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="amountUnpaid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receipts" upperBound="-1"
        eType="#//Receipt" eOpposite="#//Receipt/transaction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Receipt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transaction" lowerBound="1"
        eType="#//Transaction" eOpposite="#//Transaction/receipts"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Audit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
        eType="#//Transaction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" upperBound="-1"
        eType="#//Order"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerID" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmployeeRole" abstract="true" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" lowerBound="1"
        eType="#//Person" eOpposite="#//Person/roles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Supplier" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//ItemStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ItemStatus">
    <eLiterals name="ordered"/>
    <eLiterals name="inStore" value="1"/>
    <eLiterals name="sold" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderedDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrivalDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" eType="#//Supplier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IMS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suppliers" upperBound="-1"
        eType="#//Supplier" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managers" upperBound="-1"
        eType="#//Manager" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" upperBound="-1"
        eType="#//Order" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="audits" upperBound="-1"
        eType="#//Audit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regularemployees" upperBound="-1"
        eType="#//RegularEmployee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" upperBound="-1"
        eType="#//Customer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transactions" upperBound="-1"
        eType="#//Transaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receipts" upperBound="-1"
        eType="#//Receipt" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
